trigger:
  batch: true
  branches:
    include:
    - main
  tags:
    include:
    - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: OUT_DIR
    value: '../nupkgs'
  - name: NPM_CONFIG_CACHE
    value: $(Pipeline.Workspace)/.npm  
  - name: PROJECTS
    value: >-
      src/Clip/Clip.csproj
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages

steps:

- task: PowerShell@2
  displayName: 'Get configuration'
  inputs: 
    targetType: 'inline'
    script: |
      $configuration = 'RELEASE'
      echo "source branch = $Env:BUILD_SOURCEBRANCH"
      echo "configuration = $configuration"
      echo "##vso[task.setvariable variable=CONFIGURATION]$configuration"

- task: PowerShell@2
  displayName: 'Get version from csproj'
  inputs:
    targetType: 'inline'      
    script: |
      $xml = [Xml] (Get-Content .\Directory.Build.Props)
      $prefix = $xml.Project.PropertyGroup.VersionPrefix
      $suffix = $xml.Project.PropertyGroup.VersionSuffix
   
      echo "prefix = $prefix | suffix = $suffix | build = $Env:BUILD_BUILDID"
      
      If ($suffix) {
        echo "##vso[task.setvariable variable=VERSION]$prefix-$suffix.$Env:BUILD_BUILDID" } 
      Else { 
        echo "##vso[task.setvariable variable=VERSION]$prefix" }

- task: Cache@2
  inputs:
    key: 'nuget | "$(Agent.OS)" | ./src/Clip/packages.lock.json'
    restoreKeys: |
       nuget | "$(Agent.OS)"
    path: $(NUGET_PACKAGES)
  displayName: 'NuGet cache'

- task: Cache@2
  displayName: 'NPM cache'
  inputs:
    key: 'npm | "$(Agent.OS)" | ./src/Clip/Backoffice/package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(NPM_CONFIG_CACHE)

- task: Npm@1
  displayName: 'NPM install'
  inputs:
    command: 'install'
    workingDir: './src/Clip/Backoffice'

- task: Npm@1
  displayName: 'Build Backoffice'
  inputs:
    command: 'custom'
    workingDir: './src/Clip/Backoffice'
    customCommand: 'run prod'

- task: DotNetCoreCLI@2
  displayName: 'Restore dotnet dependencies'
  inputs:
    command: 'restore'
    projects: '$(PROJECTS)'
    feedsToUse: 'select'
    verbosityRestore: 'Minimal'

- task: DotNetCoreCLI@2
  displayName: 'Pack the Web and Backoffice projects'
  inputs:
    command: 'pack'
    packagesToPack: 'src/Clip/Clip.csproj'
    configuration: '$(CONFIGURATION)'
    packDirectory: '$(OUT_DIR)'
    includesymbols: true
    verbosityPack: Minimal
    versioningScheme: byEnvVar
    versionEnvVar: VERSION

- task: CopyFiles@2
  displayName: 'Copy package files from OutDir to staging directory'
  inputs:     
    SourceFolder: '$(OUT_DIR)'
    Contents: |
      *.nupkg
      *.snupkg
      !*.symbols.nupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish zip and nuget from staging directory'
  inputs:
    artifactName: 'Clip.Umbraco'
    targetPath: '$(Build.ArtifactStagingDirectory)'
